#!/bin/bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
#cd /disk1/you_scrapy/conf/
scrapy crawl you -a seed=seed.urls -a sites=sites.dat -a single_scrapy=true > tmp.my &
python ../you/refresh_seeds.py seed.urls &
